# Generated by Django 5.2 on 2025-04-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measures',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Measurement', 'verbose_name_plural': 'Measurements'},
        ),
        migrations.AddField(
            model_name='measures',
            name='ec',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
