# Generated by Django 5.2 on 2025-08-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='velocidad_motor',
            field=models.IntegerField(),
        ),
    ]
