# Generated by Django 5.2 on 2025-08-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_measure_velocidad_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='caudal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
