# Generated by Django 5.1.1 on 2025-04-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_suggestion_rename_measures_measure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suggestions/'),
        ),
    ]
