# Generated by Django 5.2 on 2025-08-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_measure_caudal'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='cant_botellas',
            field=models.IntegerField(default=0),
        ),
    ]
