# Generated by Django 5.2 on 2025-08-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_measure_cant_botellas'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='cant_liquido',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
