# Generated by Django 5.2 on 2025-04-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_suggestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='motor_ph_acido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measure',
            name='motor_ph_alcalino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measure',
            name='motor_tds_altos',
            field=models.BooleanField(default=False),
        ),
    ]
